<?php

namespace ProjetWebBDE\ProjetWebBDEBundle\Repository;

/**
 * commenter_photoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commenter_photoRepository extends \Doctrine\ORM\EntityRepository
{
}
