<?php

namespace ProjetWebBDE\ProjetWebBDEBundle\Repository;

/**
 * proposition_activiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proposition_activiteRepository extends \Doctrine\ORM\EntityRepository
{
}
