<?php

namespace ProjetWebBDE\ProjetWebBDEBundle\Repository;

/**
 * voterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voterRepository extends \Doctrine\ORM\EntityRepository
{
}
